reorganize project structure to comply with the pattern expected by the solution builder pipeline

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -160,9 +160,17 @@ jobs:
         # The checkout action above changes the work dir in a way that breaks
         # the docker commands in this action, so we need to specify work dir
         # explicitly here.
+        # TODO: after moving the aws-media-insights repo to aws-content-analysis, then remove the if statement at the beginning:
         working-directory: /home/runner/work/
         run: |
-          cp -R ./aws-media-insights/aws-media-insights/test .
+          if [ -d ./aws-media-insights/ ]; then
+            cp -R ./aws-media-insights/aws-media-insights/test .
+          elif [ -d ./aws-content-analysis/ ]; then
+            cp -R ./aws-content-analysis/aws-content-analysis/test .
+          else
+            echo "ERROR: Cannot find test files"
+            exit 1
+          fi
           cd test/
           echo "Building puppeteer tests"
           npm init -y
